[[language]]
name = "syphon"
scope = "scope.syphon"
injection-regex = "syphon"
file-types = ["sy"]
comment-tokens = ["#"]
indent = { tab-width = 4, unit = " " }
shebangs = ["syphon"]

[[grammar]]
name = "syphon"
source = { path = "/home/yhya/Programming/tree-sitter-syphon" }
