[[language]]
name = "syphon"
scope = "scope.syphon"
injection-regex = "syphon"
file-types = ["sy"]
comment-tokens = ["#"]
indent = { tab-width = 4, unit = " " }
shebangs = ["syphon"]

[[grammar]]
name = "syphon"
source = { path = "/home/yhya/Programming/tree-sitter-syphon" }

[[language]]
name = "barq"
scope = "scope.barq"
injection-regex = "barq"
file-types = ["bq"]
comment-tokens = ["//"]
indent = { tab-width = 4, unit = " " }
shebangs = ["barq"]

[[grammar]]
name = "barq"
source = { path = "/home/yhya/Programming/tree-sitter-barq" }
